version: "2"
checks:
  method-lines:
    config:
      threshold: 50

engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60

exclude_patterns:
  - "**/node_modules/"
  - "**/scripts/"
  - "**/__test__/*"
  - "**/*.test.js"
  - "**/*.min.js"
  - "**/*.bundle.js*"
  - "**/dist/"
  - "**/lib/"
  - "**/notebooks/"
  - "**/gap/"
  - "**/*.py"
  - "**/webpack.config.js"
  - "**/karma.conf.js"
